export default{
	friends:function(){
		let frienararr=[
			{
				id:1,
				imgurl:'fulibl3.png',
				tip:99,
				name:'海哥',
				email:'jiaogp@qq.com',
				time:new Date(),
				news:'山猪吃不来细糠'
			},
			{
				id:2,
				imgurl:'fulib1.jpg',
				tip:2,
				name:'山猪',
				email:'jiaogd@qq.com',
				time:new Date(),
				news:'山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:3,
				imgurl:'fulibl2.png',
				tip:0,
				name:'细糠',
				email:'dxsg@qq.com',
				time:'2020-3-3',
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:4,
				imgurl:'fulibl4.jpg',
				tip:5,
				name:'不来',
				email:'zdxsg@qq.com',
				time:new Date(),
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:5,
				imgurl:'fulibl2.png',
				tip:0,
				name:'细糠',
				email:'wjsg@qq.com',
				time:'2020-3-3',
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:6,
				imgurl:'fulibl4.jpg',
				tip:5,
				name:'不来',
				email:'yyhzs@qq.com',
				time:new Date(),
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:7,
				imgurl:'fulibl2.png',
				tip:0,
				name:'细糠',
				email:'wudi@qq.com',
				time:'2020-3-3',
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:8,
				imgurl:'fulibl4.jpg',
				tip:5,
				name:'不来',
				email:'sdmjm@qq.com',
				time:new Date(),
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:9,
				imgurl:'fulibl2.png',
				tip:0,
				name:'细糠',
				email:'lj@qq.com',
				time:'2020-3-3',
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:10,
				imgurl:'fulibl4.jpg',
				tip:5,
				name:'不来',
				email:'123232@qq.com',
				time:new Date(),
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:11,
				imgurl:'fulibl2.png',
				tip:0,
				name:'细糠',
				email:'123232@qq.com',
				time:'2020-3-3',
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:12,
				imgurl:'fulibl4.jpg',
				tip:5,
				name:'不来',
				email:'123232@qq.com',
				time:new Date(),
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:13,
				imgurl:'fulibl2.png',
				tip:0,
				name:'细糠',
				email:'123232@qq.com',
				time:'2020-3-3',
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			},
			{
				id:14,
				imgurl:'fulibl4.jpg',
				tip:5,
				name:'不来',
				email:'123232@qq.com',
				time:new Date(),
				news:'山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠山猪吃不来细糠'
			}
		]
		return frienararr
	},
	//好友关系
	isFriend:function(){
		let isfriend=[
			{
				userid:1,
				friend:2
			},
			{
				userid:1,
				friend:4
			},
			{
				userid:1,
				friend:7
			},
			{
				userid:1,
				friend:3
			},
			{
				userid:1,
				friend:14
			},
			{
				userid:1,
				friend:13
			},
		]
		return isfriend
	}
}